---
- name: copy fluentd rsyslog configuration
  template: src=templates/rsyslog/fluentd.conf.j2
            dest=/etc/rsyslog.d/fluentd.conf
            owner=root
            group=root
            mode=0644
  notify: restart rsyslog
